### PR TITLE
Added Delete confirmation Dialog in the details Activity

### PR DESCRIPTION
**Pull request by Bradzer**

### CODE REVIEW

**Comment by redlor** [comment]
@Bradzer thank you for the pull request!
I was looking at the code, not merged yet. I think the dialog won't survive a screen rotation, did you try it?
Let me know.
Many thanks and best wishes!

Lorenzo

**Comment by Bradzer** [comment]
@redlor 

Indeed I made the test and the dialog didn't survive the screen rotation. I started solving the issue. I made progress but still having a problem with firebase. 

Maybe you can have a look on the code. Is it okay for you ?

**Comment by redlor** [comment]
@Bradzer 
happy new year! 
Yes, I'll copy your code and make some tests as soon as I can. In the meantime, try yourself doing researches and making tests, this will help you learning new things.
The app made a lot of progresses but there are still many things to do.
Many thanks for helping.

**Comment by redlor** [comment]
@Bradzer I did some changes to the code: I removed the part to cancel the item in SQL since there is no SQL database anymore. I also added a method to keep the dialog on orientation change. In addition, there was a problem crashing the app when clicking the confirmation button: the updateFirebase class was not instantiated so I added the code to do it:

 updateFirebase = new UpdateFirebase();

I didn't test on a tablet yet but should work. I'll push later.
Thank you and keep up the good work!

**Pull request closed without merging**
