### PR TITLE
Added a confirmation dialog when deleting item in the detail activity…

### PR DESCRIPTION
**Pull request by redlor**
… and a privacy policy

### CODE REVIEW

**Comment by danielblokus** [comment]
@redlor I think there is a lot of changes for one commit...

**Comment by danielblokus** [comment]
Maybe we should justify text in the Privacy Policy view

**Comment by redlor** [comment]
eheh yes I was to lazy to create a new branch
I'll open an issue for justify the text since it is supported only from Android O.
there are some libraries to help anyway.

Thank you!

**Comment by danielblokus** [comment]
Yep, for example: https://github.com/programingjd/justified

**Pull request merged**
